name: Docker

on:
  push:
    branches: ["main"]
    tags: ["v*"]

env:
  PLATFORMS: "linux/amd64,linux/arm64"

jobs:
  build:
    name: Build and publish images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build main Sydent image
        if: github.ref_name == 'main'
        uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            matrixdotorg/sydent:main

      - name: Build release Sydent image
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            matrixdotorg/sydent:latest
            matrixdotorg/sydent:${{ github.ref_name }}
